name: sahla
description: "A New Way to Buy Things."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  folding_cell: ^1.0.2
  flutter_onboarding_slider: ^1.0.11
  firebase_auth: ^5.1.2
  simple_animated_button: ^0.0.9
  awesome_snackbar_content: ^0.1.3
  connectivity: ^3.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cloud_firestore: ^5.2.0
  uuid: ^4.4.2
  flutter_secure_storage: ^9.2.2
  splash_view: ^2.0.1
  flutter_dotenv: ^5.1.0

  firebase_core: any
  flutter_easy_dialogs: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/Logo.png
    - assets/
    - assets/onboarding_images/background1x1w.jpeg
    - assets/onboarding_images/page1.png
    - assets/onboarding_images/page2.png
    - assets/onboarding_images/page3.png
    - assets/onboarding_images/page4.png
    - assets/images/signin.png
    - assets/images/signup.jpeg
    - assets/images/Ooredoo.png
    - assets/images/Baridi.png





